[package]
name = "bitstates"
version = "0.1.0"
edition = "2024"

[dependencies]
bit_states_derive = { path = "bit_states_derive", optional = false }

[features]
default=["non-atomic"]
non-atomic=[]
atomic=[]
